# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Megan E Brown
# ModelCode.py
# Created on: 2014-04-21 23:51:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: ModelCode <Scratch_Workspace> <Trails> <Trail_Proximity> <DEM> <Min_Elevation__m_> <Max_Slope____> <Final_raster> 
# ---------------------------------------------------------------------------



import arcpy
from arcpy import env


arcpy.env.workspace=r"F:\data\john_pc2\Gabriele\BUFFER_2000_SLIPT_CLIPMAPA"
list_buffers_10000=arcpy.ListFeatureClasses()


arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\paisagens_antigas_DATA1\clips_2k_mapas_antigos"
fc='buffer_starosaviterbo_mestrado_merge'
fields="id_2"
with arcpy.da.SearchCursor(fc, fields) as cursor:
    for row in cursor:
        for i in list_buffers_10000:
            if "id2__"+`row[0]` in i:
                query="id_2=%d"%row[0]
                format="0000"+`row[0]`
                format=format[-2:]
                outpuname=i.replace(".shp","_clip2K")  
                arcpy.SelectLayerByAttribute_management(fc.replace(".shp",""),"NEW_SELECTION",query)
                arcpy.Clip_analysis(i.replace(".shp",""),fc,outpuname,"")
                arcpy.SelectLayerByAttribute_management(fc,"CLEAR_SELECTION")                


arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\paisagens_antigas_DATA1\buffer_2k_merge\split"
list_buffer_split=arcpy.ListFeatureClasses()            


arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\paisagens_antigas_DATA1\clips_2k_mapas_antigos"
list_clipMap_split=arcpy.ListFeatureClasses()            

cont_id=0
arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\paisagens_antigas_DATA1\rasters_serapados_bufer_vazio_e_clip"
for a in list_buffer_split:
    inpA=a.replace(".shp","")
    outA=a.replace(".shp","_Rast.tif")
    arcpy.AddField_management(inpA,"temp","SHORT",0,0,2)
    arcpy.CalculateField_management(inpA,"temp",0,"PYTHON_9.3","#")
    arcpy.conversion.PolygonToRaster(inpA,"temp",outA,"CELL_CENTER","NONE",10)
    
    

    
for i in list_clipMap_split:    
    inpI=i.replace(".shp","")
    outI=i.replace(".shp","_Rast.tif")
    arcpy.AddField_management(inpI,"temp","SHORT",0,0,2)
    arcpy.CalculateField_management(inpI,"temp",1,"PYTHON_9.3","#")
    arcpy.conversion.PolygonToRaster(inpI,"temp",outI,"CELL_CENTER","NONE",10)   
    cont_id=cont_id+1
    




#dados novo criadno binario

arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\Paisagens_finalizadas_para_analise_PAI2015_07_d13"
list_clipMap_split=arcpy.ListFeatureClasses()            


arcpy.env.workspace=r"E:\data_2015\___john\Gabi_mapeamento_2015_05_d28\Paisagens_finalizadas_para_analise_PAI2015_07_d13\rasters"
for i in list_clipMap_split:    
    inpI=i.replace(".shp","")
    outI=i.replace(".shp","_Rast.tif")
    arcpy.conversion.PolygonToRaster(inpI,"NEWCOD",outI,"CELL_CENTER","NONE",10)   
    